
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../types/database';

const SUPABASE_URL = "https://qtqxdihxbjsheseixjwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0cXhkaWh4YmpzaGVzZWl4andqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzc2MzUsImV4cCI6MjA2MjgxMzYzNX0.acP5r5PswXIfZxR7cLnjSRnV1VC6iNx0rgwKiaAcrlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
